function state = gaplotMAE(options, state, flag)

[~, indices] = sort(max(state.Score, [], 2));

mae_individual = state.Score(indices(1), :)';
std_pop = std(state.Score, 0, 1)';

% or NaN to plot into currently open axis?
pos = get(gca, 'OuterPosition');

% delete the existing axis?
delete(gca);

plot(plot_superpose({...
  plot_bars(mae_individual, repmat(0, length(mae_individual), 1), ...
            std_pop, [], {}, {}, ...
            ['Lowest max error individual + pop STD (iter ' num2str(state.Generation) ')'], ...
            [0 (length(mae_individual) + 1) 0 Inf], ...
            struct('dispNvals', 0)), ...
  plot_abstract({[0; (length(mae_individual) + 1)], [1 1], 'r--'}, ...
                {'', 'error^2 [STD]'}, '', {}, 'plot')}), ...
     pos); 

