function findBurstTest(plotit)

plotit = defaultValue('plotit', 0);

% if plotit is 1, produces plots
plot_props = struct('fixedSize', [16 6], 'axisLimits', [25 40 NaN NaN]);

% call runxunit in this directory to run these tests
t_he12 = ...
    trace_HE(['simhe-2synscales_input5_22B_m47_batch11_all_cond_rank7_somaVm_HE_12.genflac'], ...
             12, '5_22B', 5e-4, 1, 'input5_22B_m47_batch11_all_cond_rank7', ...
             struct('inputDir', '../../input-patterns'));

[prof_he12, intermediate_data, freerunisistats, tracedata] = ...
    getResults(t_he12, struct('HNweights', 1, 'debug', 1));
if plotit, plot(prof_he12, '', plot_props); end

% => pretty bad example, this file should not be accepted
assert(isnan(prof_he12.results.peri_phase_first), ...
       'This case should have failed - too irregular spiking');

% rank1 example
t_r1_he12 = ...
    trace_HE(['simhe-2synscales_input5_22B_m47_batch11_all_cond_rank1_somaVm_HE_12.genflac'], ...
             12, '5_22B', 5e-4, 1, 'input5_22B_m47_batch11_all_cond_rank1', ...
             struct('inputDir', '../../input-patterns'));

[prof_r1_he12, intermediate_data, freerunisistats, tracedata] = ...
    getResults(t_r1_he12, struct('HNweights', 1, 'debug', 1));
% also fails with max ipower=6 because of irregular spiking, detected
% with ipower=7
if plotit, plot(prof_r1_he12, '', plot_props); end
assert(isnan(prof_r1_he12.results.peri_phase_first), ...
       'This case should have failed - too irregular spiking');

% P condition, top model
[prof3_he12, intermediate_data, freerunisistats, tracedata] = ...
    getResults(...
      trace_HE(['simhe-2synscales_input5_22B_m47_batch8_Pcond_2syns_rank1_somaVm_HE_12.genflac'], ...
               12, '5_22B', 5e-4, 1, 'input5_22B_m47_batch8_Pcond_2syns_rank1', ...
               struct('inputDir', '../../input-patterns')), ...
      struct('HNweights', 1, 'debug', 1));
if plotit, plot(prof3_he12, '', plot_props); end

assertEqual(prof3_he12.results.peri_phase_first, ...
            0.0243146580622805273674824633189928135834634304046630859375, ...
       'P conductance + 2 syns search best model 1st peri spike mismatch.');

% 3rd one is the HN4 reference, so shouldn't change:
assert(prof3_he12.intermediate_data.firstlastraw{3}(1,1) == 23.249056, ...
       'HN4 firstlast ref broken');

% borderline slow firing case from batch2
[prof4_he8, intermediate_data, freerunisistats, tracedata] = ...
    getResults(...
      trace_HE(['simhe-2synscales_input5_22B_m47_batch2_2syns_fuzzy_bad_case_somaVm_HE_8.genflac'], ...
               8, '5_22B', 5e-4, 1, 'input5_22B_m47_batch2_2syns_fuzzy_bad_case', ...
               struct('inputDir', '../../input-patterns')), ...
      struct('HNweights', 1, 'debug', 1));
if plotit, plot(prof4_he8, '', plot_props); end

% sync case is borderline
% $$$ assertEqual(prof4_he8.results.sync_phase_first, ...
% $$$             -0.27814614004903093213982856468646787106990814208984375, ...
% $$$             '2 syns search borderline slow spike case sync phase mismatch.');

% in the sync trace, first burst starts at 23.23 s, which is very
% close to start time (23.02), so if maxISI is 420 ms, then it drops the
% first burst and fails. Therefore it lowers it down to 236 ms to accept
% the first burst. Since that is not accepted, this should be rejected:
assert(isnan(prof4_he8.results.sync_phase_first), ...
       '2 syns search sync too close to start, should not be accepted.');
